version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: ETL_Staging_container
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: ETL-Staging
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ETL_Loading_Container
    environment:
      SA_PASSWORD: "MssqlP@ssword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  postgres_data:
  mssql_data:
